import type { Metadata } from "next";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });

import Navbar from "@/components/navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head></head>
            <body>
                <Navbar />
                {children}
            </body>
            {/* <body className={inter.className}>{children}</body> */}
        </html>
    );
}
